### PR TITLE
Set `new_browser_tab` to False by default

### PR DESCRIPTION
**Pull request by yuvipanda**
IMO, this is a big breaking change that should be a
new major version. We should also try fix all the subprojects
that need fixing before we do this.

### CODE REVIEW

**Comment by yuvipanda** [comment]
/cc @ryanlovett @cmd-ntrf @consideRatio 

Apologies for not reviewing the PR adding this earlier...

**Comment by ryanlovett** [comment]
@yuvipanda Do you have a sense as to how many subprojects this breaks? The rstudio proxy has been patched, and shiny and vs-code don't need it. I'm sure there are several I'm not aware of.

In any case, a new major version would [help us sync](https://github.com/jupyterhub/jupyter-server-proxy/issues/197) the package and lab plugin versions. :)

**Comment by yuvipanda** [comment]
Right, I think what we could do is:

1. Merge this, cut a new version that's a minor bump
2. Revert this, cut a new version that's a major bump

This way, we don't accidentally break people, since this *is* a major change. What do you think?

**Comment by yuvipanda** [comment]
I am mostly worried about people with their own deployments, running their own applications with config.py files scattered around. This will break them, especially if they are using [framebusting](https://en.wikipedia.org/wiki/Framekiller).

**Comment by yuvipanda** [comment]
I'd also personally think that 99% of apps here do *not* want to be iframed - it's an external facing app that someone wants to run under JupyterHub. Having very different behavior when launched from JupyterLab vs Classic Notebook is also very confusing IMO. So I'd still actually prefer for this to be opt-in rather than opt-out.

**Comment by ryanlovett** [comment]
@cmd-ntrf How do you feel about @yuvipanda's concerns?

**Comment by cmd-ntrf** [comment]
I think both options are valid, and I played with both when implementing PR #193, so I have nothing against reverting `new_browser_tab` to True as default. It makes sense given previous behavior of jupyter-server-proxy and wait for a major version release to change the default if this is what it is decided.

That said, on the long-term, I think the default behavior should be to open a JupyterLab tab.
- JupyterLab users except launcher items to start a new tab and as time goes by, there will be more users that are only familiar with JupyterLab, limiting the potential confusion. I do not think the extension behavior in the classic Notebook should be taken into account when making user-experience decision for the JupyterLab extension.
- There are other extensions proxying web app in JupyterLab, like [jupyterlab_tensorboard](https://github.com/chaoleili/jupyterlab_tensorboard), that open new JupyterLab tab. I think the demand for that sort of integration in JupyterLab is bigger than 1%. Being able to have a web app next to a notebook or a terminal has a lot of potential. RStudio or VS Code next to a notebook is a bit quirky, I agree, but I think there are more use cases that would benefit from being in a tab.
- The Wikipedia article on framebusting mentions the technique is idempotent when put in an HTML5 iframe with the sandbox attribute, which is what is used by JupyterLab iframe widget.

**Comment by yuvipanda** [comment]
First, I'm extremely in awe that this functionality exists, and can be toggled on with a simple flag. Thank you very much for pushing this through, @cmd-ntrf!

Interestingly, I see jupyter-server-proxy's first goal as allowing arbitrary applications (like rstudio) to run under JupyterHub as first-class-citizens in full-screen ways. For example, at Berkeley, way more people use RStudio via this method than JupyterLab in any form. Classic notebook is what most people use to teach (at Berkeley and elsewhere, I think) and I don't think that's going away anytime soon. So I haven't really thought of the primary-JupyterLab use case so far.

Either way, I think change in the default behavior should definitely be a major version bump, not a minor. What do you think of that?

**Comment by betatim** [comment]
I had seen the PR to add this functionality but was surprised when debugging my vscode binder (for unrelated reasons) to notice that vs code was now in a jupyterlab tab. I added code to https://github.com/betatim/vscode-binder/tree/master to make it open in a new browser tab as before. (As some feedback on which setting is "the right default value")

However I am always massively in favour of not changing existing behaviour for existing users, even if it is an improvement. It is super tedious for me as a maintainer to stick to that rule but Tim-the-user-of-software hates nothing more than stuff changing behaviour for "no good reason" (based on the fact that I was a happy user of the status quo :D )

**Comment by manics** [comment]
_If_ it's the new default I think this is definitely a breaking change:
- it's a major UI change for users
- it breaks many existing configurations

**Comment by cmd-ntrf** [comment]
2 nights of sleep later, I think this PR is a no-brainer.

I will make sure in the future to not break with default behavior when introducing new changes, and trust me, there is more to come ;).

**Comment by betatim** [comment]
Thanks everyone for the fast and friendly resolution!

**Pull request merged**
