### PR TITLE
Move proxy_request_options to configuration.

### PR DESCRIPTION
**Pull request by ryanlovett**
To address #112.

### CODE REVIEW

**Comment by ryanlovett** [comment]
Example app that requires a proxy request option:
https://github.com/ryanlovett/jupyter-syncthing

**Comment by yuvipanda** [comment]
This is awesome, and we should definitely support configuring timeouts. However, I think we should explicitly support them, since otherwise we will be tied down to Tornado's HTTP Client implementation. I'd love to move to aiohttp at some point.

**Comment by costa** [comment]
Hello, thank you for your effort.

I need to configure jupyterhub proxy timeouts (without monkey-patching the code preferably).

I'll just wait for this to be merged, right?

It cannot take long, definitely under half a year, right?

**Comment by manics** [comment]
@costa Are you able to help test this?

**Comment by costa** [comment]
@manics Let's see, I'm using the JupyterHub helm chart with a custom-built singleuser image which is built with installing `jupyter-server-proxy` through pip; I guess I can install a custom version of that to produce a test image to use with a test JupyterHub deployment — if it is not too much effort to do so.

**Comment by costa** [comment]
Guys (no assumption here ;)), this PR has conflicts, I'm probably willing to test this if I have a chance to change the proxy request timeout without having to monkey-patch the code myself — and anyone can (fix the conflicts and) confirm it's worth the effort.

**Comment by yuvipanda** [comment]
> It cannot take long, definitely under half a year, right?

:D 

I think unfortunately this PR didn't make it.

While we do have a process ready timeout (https://github.com/jupyterhub/jupyter-server-proxy/blob/75cba2cef9765d56aa5374bb6de7d4d89a59cbf3/docs/source/server-process.md?plain=1#L41) we don't have a request timeout.

I think we should implement request timeout as its own option, rather than allowing arbitrary options to be passed through. That exposes internal detail of the project (which http client it uses) outside, making it impossible to change.

With that, I'm going to close this.

**Pull request closed without merging**
