### PR TITLE
Configure absolute and server URL prefixes

### PR DESCRIPTION
**Pull request by manics**
This started off as a fix for the `X-Forwarded-Context` `X-ProxyContextPath`. Previously they were always `/proxy/{port}`, now they should be `/server-name` if this is a managed server. Since this is related to the code that controls the URL rewriting I thought I'd add in support for absolute URLs.

I've done some testing with:
```
c.ServerProxy.servers = {
    'python-http': {
        'command': ['python3', '-m', 'http.server', '{port}'],
    },
    'python-http-abs': {
        'command': ['python3', '-m', 'http.server', '{port}'],
        'rewrite': '',
    },
}
```
`python-http` should produce logs like
```
"GET / HTTP/1.1" 200 -
```
`python-http-abs` should produce logs like
```
"GET /python-http-abs/ HTTP/1.1" 404 -
```
Also `/proxy-abs/port` is the absolute version of `/proxy/port`

Needs more testing! @jacobtomlinson @psychemedia 

Closes https://github.com/jupyterhub/jupyter-server-proxy/issues/43

### CODE REVIEW

**Comment by manics** [comment]
I've changed the config name from `absolute: False|True` to `rewrite: "/"|""` to match the terminology typically used when configuring web-servers and proxies, e.g. https://github.com/kubernetes/ingress-nginx/tree/nginx-0.21.0/docs/examples/rewrite

The prefix for ports without rewriting is still `/proxy-abs/port` though alternatives could be `/proxyp/{port}` (for proxy-passthrough) or `/passthrough/{port}`. What do you think?

**Comment by yuvipanda** [comment]
w00t, this is awesome. I'll try take a closer look later today.

Vague first thoughts:

1. Are there ways we can do this without extra classes / inheritance? 
2. How about `/proxy/absolute`? That way we can do `/proxy/<options-string>` later if need be.

**Comment by manics** [comment]
> Are there ways we can do this without extra classes / inheritance?

Yes, I think it's possible to combine the classes and use a more complex URL match, I'll give it a go

> How about /proxy/absolute

👍

**Comment by manics** [comment]
Oops accidentally closed this .... reopened at https://github.com/jupyterhub/jupyter-server-proxy/pull/85

**Pull request closed without merging**
