### PR TITLE
Bump version number

### PR DESCRIPTION
**Pull request by yuvipanda**
Bump for #230

### CODE REVIEW

**Comment by yuvipanda** [comment]
Should unbreak Python 3.9.

**Review by ryanlovett — APPROVED** [review]
+1. Can you also please add a v1.5.3 tag?

**Review by consideRatio — APPROVED** [review]
LGTM!

**Comment by consideRatio** [comment]
@ryanlovett and @yuvipanda I cut a 1.5.3 release: https://pypi.org/project/jupyter-server-proxy/

**Pull request merged**
