### PR TITLE
[WIP] Use GitHub actions for CI

### PR DESCRIPTION
**Pull request by oeway**
Following a discussion in https://github.com/jupyterhub/jupyter-server-proxy/pull/181, would be good if we can run tests with a CI that support Windows. It turns out Travis doesn't support Windows/OSX for Python.

This PR replaces Travis CI with Github Actions, it run tests on the following matrix:
```
os: [ubuntu-latest, macos-latest, windows-latest]
python-version: [3.5, 3.6, 3.7, 3.8]
```
See an example output [here](https://github.com/oeway/jupyter-server-proxy/actions/runs/63817147), the tests fails on all windows versions and Python 3.5 on OSX.

### CODE REVIEW

**Comment by manics** [comment]
Thanks for looking into Github actions. I haven't reviewed this yet, however would you mind bringing Travis back? It's used in other JupyterHub repos so most people are familiar with it, and more importantly we'll want to add [automatic PyPi and NPM deployments](https://github.com/jupyterhub/jupyter-server-proxy/issues/175) here. This deployment process is worked out for other repos so it'd be good not to use a different process here. As far as I know it should be fine to have both Travis and GitHub actions active.

**Comment by oeway** [comment]
> Thanks for looking into Github actions. I haven't reviewed this yet, however would you mind bringing Travis back? It's used in other JupyterHub repos so most people are familiar with it, and more importantly we'll want to add [automatic PyPi and NPM deployments](https://github.com/jupyterhub/jupyter-server-proxy/issues/175) to this project at some point. This deployment process is worked out for other repos so it'd be good not to use a different process here. As far as I know it should be fine to have both Travis and GitHub actions active.

Sure, will do.
BTW, we have also been using Github Actions to do deployment to npm in [another project](https://github.com/imjoy-team/imjoy-core/blob/4e45ee39cf0d8a2896696ad28e183ea89cf71dd7/.github/workflows/build-library.yml#L80-L87). Being switched from Travis to Github Actions, my general feeling is it's even easier to setup. For example, you don't need to generate encrypted tokens, but store them directly to github settings.

For this PR, I still have some connection issues with all windows machine at the moment: https://github.com/oeway/jupyter-server-proxy/runs/536606938?check_suite_focus=true#step:6:70
Will try to fix it.

**Comment by consideRatio** [comment]
@oeway thanks for your work on this project! :heart: :tada:!

Could you squash the commits a bit before merge also? While debugging #185 it became a bit harder [looking here](https://github.com/jupyterhub/jupyter-server-proxy/commits?author=oeway) because there were plenty of commits in sequence that changed something of relevance back and forth.

To "squash" or "fixup" some commits, you can work with `git rebase -i master` and then you'll need to do a force push.

**Comment by oeway** [comment]
@consideRatio This PR is not done yet, there is a connection issue with the windows machines. I am quite busy at the moment and will take more time to investigate.

Thanks for the suggestion. I will do a cleanup when it’s done. 

Meanwhile, one can also select the “Squash and Commit ” option when merging the PR. Or perhaps enable that by default for this repo. What do you think?

**Comment by consideRatio** [comment]
@oeway no worries, thank you for your contributions!! :heart: :tada:

We have typically defaulted to always merging in the JupyterHub organizations repositories. And at the moment I'm cautious to changing from this as squashing on GitHub apparently now cause the authorship to be replaced with the person pressing squash and merge, as [happened here](https://github.com/bokeh/jupyter_bokeh/pull/90) for example.

**Comment by betatim** [comment]
Maybe a quick win for dealing with failing Python 3.5 tests is to declare Python 3.5 unsupported. The [3.5 series will be end-of-life'd in September this year](https://devguide.python.org/#branchstatus).

**Comment by oeway** [comment]
Update: I cannot get the window CI working, after hours of trying different options I could not get the windows version to work.

I started to configure the CI to upload jupyter notebook output log, and here is what I found:
```
[E 06:59:01.386 NotebookApp] 500 GET /python-http/abc?token=secret (::1) 15.58ms referer=None
[E 06:59:01.401 NotebookApp] Uncaught exception GET /python-http-abs/def?token=secret (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/python-http-abs/def?token=secret', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\websocket.py", line 97, in get
        return await self.http_get(*args, **kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\handlers.py", line 540, in http_get
        return await self.proxy(self.port, path)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\handlers.py", line 534, in proxy
        await self.ensure_process()
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\handlers.py", line 484, in ensure_process
        await loop.run_in_executor(None, start_thread)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\handlers.py", line 481, in start_thread
        new_loop.run_until_complete(self._ensure_process())
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\base_events.py", line 583, in run_until_complete
        return future.result()
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\jupyter_server_proxy\handlers.py", line 512, in _ensure_process
        await proc.start()
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\simpervisor\process.py", line 91, in start
        *self._proc_args, **self._proc_kwargs
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
        stderr=stderr, **kwds)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\base_events.py", line 1540, in subprocess_exec
        bufsize, **kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\windows_events.py", line 372, in _make_subprocess_transport
        **kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\base_subprocess.py", line 37, in __init__
        stderr=stderr, bufsize=bufsize, **kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\windows_events.py", line 819, in _start
        bufsize=bufsize, **kwargs)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\asyncio\windows_utils.py", line 155, in __init__
        stderr=stderr_wfd, **kwds)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "c:\hostedtoolcache\windows\python\3.7.6\x64\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Any idea how to fix this error on windows?

@betatim @consideRatio @yuvipanda

**Comment by oeway** [comment]
Will close this PR since I cannot get it to work.

**Pull request closed without merging**
