### PR TITLE
Proxy Websocket subprotocols

### LINKED ISSUE #179: Subprotocols issue with bokeh
Here's my code:

```
import random
from bokeh.server.server import Server
from bokeh.application import Application
from bokeh.application.handlers.function import FunctionHandler
from bokeh.plotting import figure, ColumnDataSource
def make_document(doc):
    source = ColumnDataSource({'x': [], 'y': [], 'color': []})

    def update():
        new = {'x': [random.random()],
               'y': [random.random()],
               'color': [random.choice(['red'])]}
        source.stream(new)

    doc.add_periodic_callback(update, 100)

    fig = figure(title='Streaming Circle Plot!', sizing_mode='scale_width',
                 x_range=[0, 1], y_range=[0, 1])
    fig.circle(source=source, x='x', y='y', color='color', size=10)

    doc.title = "Now with live updating!"
    doc.add_root(fig)
    
def make_document2(doc):
    source = ColumnDataSource({'x': [], 'y': [], 'color': []})

    def update():
        new = {'x': [random.random()],
               'y': [random.random()],
               'color': [random.choice(['green'])]}
        source.stream(new)

    doc.add_periodic_callback(update, 100)

    fig = figure(title='Streaming Circle Plot!', sizing_mode='scale_width',
                 x_range=[0, 1], y_range=[0, 1])
    fig.circle(source=source, x='x', y='y', color='color', size=10)

    doc.title = "Now with live updating!"
    doc.add_root(fig)

apps = {'/r1': Application(FunctionHandler(make_document)), '/r2': Application(FunctionHandler(make_document2))}

server = Server(apps, port=5001, allow_websocket_origin=["*"])
server.start()

```
Now if I go to 192.168.1.75:5001/r1 everything works. But if I go to 192.168.1.75:8888/proxy/5001/r1 I get a blank page and errors in the notebook console.

The notebook console outputs the following:
```
[I 14:38:06.551 LabApp] Client sent subprotocols: ['bokeh', 'eyJzZXNzaW9uX2lkIjogInNUVHdqWkM0Sk83dmpGeWZXeUFhc2VySnFhNzdPVm1wMDFUVERRQ1VHcGMxIiwgInNlc3Npb25fZXhwaXJ5IjogMTU4NDYyODk4NSwgImhlYWRlcnMiOiB7Ikhvc3QiOiAiMTkyLjE2OC4xLjc1Ojg4ODgiLCAiQ29ubmVjdGlvbiI6ICJrZWVwLWFsaXZlIiwgIkNhY2hlLUNvbnRyb2wiOiAibWF4LWFnZT0wIiwgIlVwZ3JhZGUtSW5zZWN1cmUtUmVxdWVzdHMiOiAiMSIsICJVc2VyLUFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS84MC4wLjM5ODcuMTQ5IFNhZmFyaS81MzcuMzYiLCAiQWNjZXB0IjogInRleHQvaHRtbCxhcHBsaWNhdGlvbi94aHRtbCt4bWwsYXBwbGljYXRpb24veG1sO3E9MC45LGltYWdlL3dlYnAsaW1hZ2UvYXBuZywqLyo7cT0wLjgsYXBwbGljYXRpb24vc2lnbmVkLWV4Y2hhbmdlO3Y9YjM7cT0wLjkiLCAiQWNjZXB0LUVuY29kaW5nIjogImd6aXAiLCAiQWNjZXB0LUxhbmd1YWdlIjogImVuLVVTLGVuO3E9MC45IiwgIkNvb2tpZSI6ICJfeHNyZj0yfDI1NzdiZTY5fGZjMmQzNzA3Zjg4ZDg5NDBlMzM0ZWFlMmFlOWUxZjY5fDE1ODQxMzU4MjE7IHVzZXJuYW1lLTE5Mi0xNjgtMS03NS04ODg4PVwiMnwxOjB8MTA6MTU4NDYyNTQ2MXwyNjp1c2VybmFtZS0xOTItMTY4LTEtNzUtODg4OHw0NDpOalZsTkdWaE1ERmpOV0ZoTkRNMk9XRmpOR1U1TUdZd1lqUTFORFF3TXpZPXxlZmJlN2U4YTNkOWRkMDUyMGI3MjhhMWE0NjdiMWJhYjI5ZGMwZmRkNmQ2YWFmYzA0YzNhOTZlZjY3MDg4MWM5XCIiLCAiSWYtTm9uZS1NYXRjaCI6ICJcImRlYTcyOTgwZjBkOTE1YzhjMWM4MGFiYzA5ZDY1NmFhMDkxNmM3ZGZcIiIsICJYLUZvcndhcmRlZC1Db250ZXh0IjogIi9wcm94eS81MDAxIiwgIlgtUHJveHljb250ZXh0cGF0aCI6ICIvcHJveHkvNTAwMSJ9LCAiY29va2llcyI6IHsiX3hzcmYiOiAiMnwyNTc3YmU2OXxmYzJkMzcwN2Y4OGQ4OTQwZTMzNGVhZTJhZTllMWY2OXwxNTg0MTM1ODIxIiwgInVzZXJuYW1lLTE5Mi0xNjgtMS03NS04ODg4IjogIjJ8MTowfDEwOjE1ODQ2MjU0NjF8MjY6dXNlcm5hbWUtMTkyLTE2OC0xLTc1LTg4ODh8NDQ6TmpWbE5HVmhNREZqTldGaE5ETTJPV0ZqTkdVNU1HWXdZalExTkRRd016WT18ZWZiZTdlOGEzZDlkZDA1MjBiNzI4YTFhNDY3YjFiYWIyOWRjMGZkZDZkNmFhZmMwNGMzYTk2ZWY2NzA4ODFjOSJ9fQ']
[I 14:38:06.552 LabApp] Trying to establish websocket connection to ws://localhost:5001/r1/ws
[I 14:38:06.555 LabApp] Websocket connection established to ws://localhost:5001/r1/ws
ERROR:tornado.application:Uncaught exception GET /r1/ws (::1)
HTTPServerRequest(protocol='http', host='192.168.1.75:8888', method='GET', uri='/r1/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
```

Chrome console gives the following error:
```
[bokeh] Failed to load Bokeh session guu6l3C2t9Yty1ZFekmjg9tzXqiQKrd7hzVvkApBK1uJ: Error: Lost websocket connection, 1006 ()
t.add_document_from_session @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:536
async function (async)
t.add_document_from_session @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:536
g @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:146
(anonymous) @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:146
(anonymous) @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:171
requestAnimationFrame (async)
(anonymous) @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:171
t.defer @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:171
n.embed_items @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:146
embed_document @ (index):58
(anonymous) @ (index):62
(anonymous) @ (index):78
o.safely @ bokeh.min.js?v=545398055367f7e60a67590a85ade60b:545
fn @ (index):52

```

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #179

### CODE REVIEW

**Comment by ryanlovett** [comment]
This looks great, thanks!

@xhochy Do you or anyone else feel its worthwhile to make the feature available by configuration too rather than only subclasses? I see no reason not to merge as-is though, and add the configuration ability later, if there's a need.

**Comment by xhochy** [comment]
What do you mean by "available by configuration"? The feature here is just a pass-through of a connection attribute through the proxy.

**Comment by ryanlovett** [comment]
Sorry, brain freeze. I shouldn't review patches on mobile.

**Comment by xhochy** [comment]
Thanks @ryanlovett!

**Comment by xhochy** [comment]
@ryanlovett @betatim Can you tag us a release? We see quite a lot issue reports popping up with this in combination with `bokeh>=2`:

* https://github.com/dask/dask/issues/6035
* https://github.com/dask/dask-labextension/pull/122
* https://github.com/dask/dask-labextension/issues/121
* https://github.com/dask/distributed/issues/3593

This would help us a lot.

**Comment by ryanlovett** [comment]
Done! v1.3.0 tagged and uploaded to pypi.

**Pull request merged**
