### PR TITLE
Add changelog for 3.1.0 (already released) and 3.2.0 (unreleased)

### LINKED ISSUE #302: Documentation bug: path_info isn't nested correctly under launcher_entry
Note to self to fix this nesting https://github.com/jupyterhub/jupyter-server-proxy/pull/279/files#diff-903467c33ed562fa960d8c2a468d97b64e196aa6434eb5ad8aa3e174ff7c8217R171-R197

### PR DESCRIPTION
**Pull request by consideRatio**
I just figured we should try cut releases somewhat regularly, and that it could be about time to do so.

I'll consider a merge of this PR as a signal to make a release as well btw.

### Try to label PRs

Note that if we label PRs ahead of time with new/enhancement/bug/maintenance, the cli `github-activity` will automatically help us when we create the CHANGELOG.md file. If you merge a PR.

### Commits part of this PR

I've added a documentation typo as part of this PR.

- Fix headings in changelog
- Add changelog for v3.1.0
- Add changelog for v3.2.0
- Fix documentation typo about launcher_entry.path_info (Closes #302)

### CODE REVIEW

**Review by yuvipanda — CHANGES_REQUESTED** [review]
I want us to wait until #301 is merged, as it modifies the extension interface introduced in #209

**Comment by ryanlovett** [comment]
Thanks @consideRatio ! If possible I'd like to wait for #301 to be merged since it enhances #209. I did just tag it with `enhancement` per your suggestion. I think it is nearly complete.

Thank you also for fixing #302!

Lastly, how does `new` differ from `enhancement` when it comes to PRs? ("this PR adds something new" vs. "this PR is an enhancement") Maybe `new` means something different here?

**Comment by ryanlovett** [comment]
@yuvipanda "Jinx, you owe me a coke."

**Review by ryanlovett — APPROVED** [review]
#301 was just merged! Maybe it goes under "New features added" even though it is an enhancement?

**Comment by consideRatio** [comment]
Thanks for quick feedback and work to unblock a release @yuvipanda and @ryanlovett !

Should this be 4.0.0 or 3.2.0 after #301 btw? Im asking from my mobile, maybe the amswer is obviously 3.2.0 or so but it would be nice nice to have an explicit agreement.

I suggest "new" means a new config option or functionality, while if the same functionality behaves better in some way or is just extended to some degree - that it is considered an enhancement. It isnt in any way black and white in all situations. It isn't a big deal if we label it incorrectly either, it is better than not having a label at all to categorize the PR.

**Comment by yuvipanda** [comment]
@consideRatio no breaking changes in any released version, so let's make it 3.2.0

**Comment by ryanlovett** [comment]
Okay, thanks for the clarification @consideRatio. I went back and changed the label on that PR.

I'm fine with either version bump.

**Comment by consideRatio** [comment]
I'd like to see https://github.com/jupyterhub/jupyter-server-proxy/pull/304 get included in this PR as well, so that feature is added in a more mature form.

**Comment by yuvipanda** [comment]
Yay release!

**Pull request merged**
