### PR TITLE
Use sanitised result of selected_subprotocol

### PR DESCRIPTION
**Pull request by benz0li**
- Fix https://github.com/jupyterhub/jupyter-server-proxy/issues/442
- Fix https://github.com/jupyterhub/jupyter-server-proxy/issues/445

### CODE REVIEW

**Comment by benz0li** [comment]
FYI @sylvaticus Fixed version deployed at https://coder.jupyter.b-data.ch.

---

```bash
cd /usr/local/lib/python3.11/site-packages/jupyter_server_proxy \
  && cp -a handlers.py handlers.py.orig \
  && sed -i 's/subprotocols=self\.subprotocols/subprotocols=self\.select_subprotocol(self\.subprotocols)/g' handlers.py
```

ℹ️ `/usr/local/lib/python3.11/site-packages/` is where Jupyter Server Proxy is installed in my setup. Adapt to your setup.

**Comment by benz0li** [comment]
Ping @consideRatio

FYI @duytnguyendtn

**Comment by sylvaticus** [comment]
I confirm that the sanitation applied to `handlers.py` solves the issue with the VSCode extension LaTex-Workshop, thank you very much...

**Comment by benz0li** [comment]
Alternatively `subprotocols=self.selected_subprotcol` as described in https://github.com/jupyterhub/jupyter-server-proxy/issues/442.

**Comment by duytnguyendtn** [comment]
Thanks for putting together this PR! Hopefully we can get some traction from the devs and get this merged

**Comment by consideRatio** [comment]
Thank you for digging into this topic @benz0li!!!

For a merge this needs to be vetted with regards to "is this a breaking change" and "is this secure" for example, things that i personally struggle with in this tech-context. It would be very helpful for me if you could provide your take on that @benz0li, it would be a great starting point for me to review this change proposal.

**Comment by benz0li** [comment]
> It would be very helpful for me if you could provide your take on that @benz0li, it would be a great starting point for me to review this change proposal.

@consideRatio You find the technical details in https://github.com/jupyterhub/jupyter-server-proxy/issues/442.

`self.select_subprotcol(self.subprotocols)` did not work, so I deleted (override function) `select_subprotocol` in `handlers.py` and went for (tornados) `self.selected_subprotcol`.

Technically, I am not up to such things either. Maybe @duytnguyendtn has more insight.

**Comment by duytnguyendtn** [comment]
Haha and you've discovered why I didn't feel brave enough to author the PR! Frankly, I don't have the background to evaluate the safety or the "breaking" nature of this change. I hoped to open a discussion in #442 with the maintainers to help evaluate it's safety and compatibility. Echoing @benz0li, @consideRatio please take a look at my investigation in #442 where I arrived at the two potential solutions at the bottom which @benz0li is basing this PR off of. I tried to make it as thorough as I could and explore the code traces.

Please let me know if I can be of any further assistance!

**Comment by benz0li** [comment]
Because Jupyter Server Proxy borrows a lot from [Tornado Web Server](https://github.com/tornadoweb/tornado), I dare to ping @bdarnell in this case.

IMHO `self.subprotocols` and `self.selected_subprotcol` return different results in one case only: When there is no subprotocol proposed.

Former vs latter:

1. Subprotocol: `[]` vs `None`
2. Header: `Sec-Websocket-Protocol:` vs 'not sent'
3. Connection: Aborted (in some cases) vs 'successfully established'

Maybe there is a simpler and saner way to prevent `subprotocols=[]` when there is no subprotocol proposed.

**Comment by benz0li** [comment]
Closed in favour of https://github.com/jupyterhub/jupyter-server-proxy/pull/448.

**Pull request closed without merging**
