### PR TITLE
Fix WebSocket race condition

### PR DESCRIPTION
**Pull request by tibdex**
Before this fix, we could go through https://github.com/jupyterhub/jupyter-server-proxy/blob/90401f1290bc3c5b9408392f8f3b93bde5f55919/jupyter_server_proxy/handlers.py#L82-L83 before the future here https://github.com/jupyterhub/jupyter-server-proxy/blob/90401f1290bc3c5b9408392f8f3b93bde5f55919/jupyter_server_proxy/handlers.py#L262-L263 resolves.

### CODE REVIEW

**Comment by tibdex** [comment]
Hello, it's been almost a month without replies. Is there something I can do to help get this fixed and published on PyPI?

**Comment by manics** [comment]
The change sounds reasonable to me, but I don't have enough knowledge of async/await to review it. Hopefully someone else can.

**Comment by betatim** [comment]
Thanks!

**Comment by betatim** [comment]
To get a release quickly some work on extending the travis.yml would help so that releases happen automatically when we tag a release. Right now someone has to do the releasing manually which means it doesn't get done very often :-/

**Comment by ryanlovett** [comment]
@betatim Could you please file an issue for that? :)

**Pull request merged**
